---
id: Mail
name: Mail
full: Mail library
description: A library that provides interfaces for sending e-mail messages and parsing e-mail addresses.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Mail
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.6.6
  api: 2.6.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Idna: ^1
      pear.horde.org/Horde_Mime: ^2
      pear.horde.org/Horde_Stream_Filter: ^2
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.horde.org/Horde_Smtp: ^1.7
      pear.horde.org/Horde_Stream_Wrapper: ^2.1
      pear.horde.org/Horde_Test: ^2.1
      pear.php.net/Net_DNS2: '*'
      pear.php.net/Net_SMTP: ^1.6
